### ISSUE TITLE
FSOE setup in ESI files

### ISSUE THREAD

**Issue by mictas** [rtlabs-com/fsoe-soem-demo#2]
Hello,
we have developed a motor Drive with  the FSoE Slave function, and  we need to define  the ESI file including the FSoE function.
We have all the relevant ETG documents, but  we don’t have any example of an ESI file which includes the FSoE functions.
Can you help us?
Thank you.
Best regards.

**Comment by nakarlsson** [comment]
Try: 
https://download.beckhoff.com/download/configuration-files/automation/twinsafe/elx9xx/esi_elx9xx.zip

**Comment by mictas** [comment]
Thank you very much.
